before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test
  - source /tmp/test/bin/activate
  - pip install .

stages:
  - test

test_python3:
  image: registry.nic.cz/turris/foris-ci/python3
  script:
    - python setup.py test --addopts="--backend openwrt --backend mock"

flake8:
  image: registry.nic.cz/turris/foris-ci/python3
  stage: test
  script:
    - python setup.py flake8
